#!/usr/bin/env node
/**
 * Generate src/icons.ts from lucide-static.
 *
 * Icons are never hand-drawn (see DESIGN.md). This script copies the exact path
 * data out of the lucide package so the browser bundle carries only the glyphs
 * the UI uses, with no runtime dependency.
 *
 * Usage:  node scripts/gen-icons.mjs
 */
import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..");
const iconDir = join(root, "node_modules", "lucide-static", "icons");

// Every icon the interface actually renders. Keeping the list explicit means an
// unused icon can never sneak into the bundle, and a missing one fails the build
// instead of rendering an empty box at runtime.
const ICONS = [
  "activity",
  "arrow-left",
  "arrow-up",
  "brain",
  "check",
  "chevron-down",
  "chevron-right",
  "circle-alert",
  "circle-check",
  "clock",
  "copy",
  "gauge",
  "inbox",
  "loader-circle",
  "menu",
  "message-square",
  "panel-left",
  "plug",
  "plus",
  "power",
  "refresh-cw",
  "search",
  "send",
  "settings",
  "sparkles",
  "square",
  "terminal",
  "trash-2",
  "triangle-alert",
  "x",
];

if (!existsSync(iconDir)) {
  console.error(`lucide-static not installed at ${iconDir}. Run: npm install`);
  process.exit(1);
}

const out = [];
const missing = [];

for (const name of ICONS) {
  const file = join(iconDir, `${name}.svg`);
  if (!existsSync(file)) {
    missing.push(name);
    continue;
  }
  const svg = readFileSync(file, "utf8");
  // Keep only the inner geometry: the wrapper is built at runtime so stroke
  // width, colour and size stay under one set of tokens.
  const inner = svg
    .replace(/^[\s\S]*?<svg[^>]*>/, "")
    .replace(/<\/svg>[\s\S]*$/, "")
    .replace(/\s+/g, " ")
    .trim();
  const paths = [...inner.matchAll(/<(path|circle|rect|line|polyline|polygon|ellipse)\b[^>]*\/?>/g)].map(
    (m) => m[0],
  );
  out.push({ name, paths });
}

if (missing.length > 0) {
  console.error(`Missing icons in lucide-static: ${missing.join(", ")}`);
  process.exit(1);
}

const body = `// Generated by scripts/gen-icons.mjs. Do not edit by hand.
// Source: lucide-static (ISC licence). One icon family only.

export type IconName =
${out.map((i) => `  | ${JSON.stringify(i.name)}`).join("\n")};

interface IconShape {
  readonly paths: readonly string[];
}

export const ICONS: Readonly<Record<IconName, IconShape>> = {
${out
  .map(
    (i) =>
      `  ${JSON.stringify(i.name)}: { paths: [\n${i.paths
        .map((p) => `    ${JSON.stringify(p)},`)
        .join("\n")}\n  ] },`,
  )
  .join("\n")}
} as const;
`;

mkdirSync(join(root, "src"), { recursive: true });
writeFileSync(join(root, "src", "icons.ts"), body, "utf8");
console.log(`src/icons.ts written: ${out.length} icons, ${out.reduce((n, i) => n + i.paths.length, 0)} shapes`);
