// Generated by scripts/gen-icons.mjs. Do not edit by hand.
// Source: lucide-static (ISC licence). One icon family only.

export type IconName =
  | "activity"
  | "arrow-left"
  | "arrow-up"
  | "brain"
  | "check"
  | "chevron-down"
  | "chevron-right"
  | "circle-alert"
  | "circle-check"
  | "clock"
  | "copy"
  | "gauge"
  | "inbox"
  | "loader-circle"
  | "menu"
  | "message-square"
  | "panel-left"
  | "plug"
  | "plus"
  | "power"
  | "refresh-cw"
  | "search"
  | "send"
  | "settings"
  | "sparkles"
  | "square"
  | "terminal"
  | "trash-2"
  | "triangle-alert"
  | "x";

interface IconShape {
  readonly paths: readonly string[];
}

export const ICONS: Readonly<Record<IconName, IconShape>> = {
  "activity": { paths: [
    "<path d=\"M22 12h-2.48a2 2 0 0 0-1.93 1.46l-2.35 8.36a.25.25 0 0 1-.48 0L9.24 2.18a.25.25 0 0 0-.48 0l-2.35 8.36A2 2 0 0 1 4.49 12H2\" />",
  ] },
  "arrow-left": { paths: [
    "<path d=\"m12 19-7-7 7-7\" />",
    "<path d=\"M19 12H5\" />",
  ] },
  "arrow-up": { paths: [
    "<path d=\"m5 12 7-7 7 7\" />",
    "<path d=\"M12 19V5\" />",
  ] },
  "brain": { paths: [
    "<path d=\"M12 18V5\" />",
    "<path d=\"M15 13a4.17 4.17 0 0 1-3-4 4.17 4.17 0 0 1-3 4\" />",
    "<path d=\"M17.598 6.5A3 3 0 1 0 12 5a3 3 0 1 0-5.598 1.5\" />",
    "<path d=\"M17.997 5.125a4 4 0 0 1 2.526 5.77\" />",
    "<path d=\"M18 18a4 4 0 0 0 2-7.464\" />",
    "<path d=\"M19.967 17.483A4 4 0 1 1 12 18a4 4 0 1 1-7.967-.517\" />",
    "<path d=\"M6 18a4 4 0 0 1-2-7.464\" />",
    "<path d=\"M6.003 5.125a4 4 0 0 0-2.526 5.77\" />",
  ] },
  "check": { paths: [
    "<path d=\"M20 6 9 17l-5-5\" />",
  ] },
  "chevron-down": { paths: [
    "<path d=\"m6 9 6 6 6-6\" />",
  ] },
  "chevron-right": { paths: [
    "<path d=\"m9 18 6-6-6-6\" />",
  ] },
  "circle-alert": { paths: [
    "<circle cx=\"12\" cy=\"12\" r=\"10\" />",
    "<line x1=\"12\" x2=\"12\" y1=\"8\" y2=\"12\" />",
    "<line x1=\"12\" x2=\"12.01\" y1=\"16\" y2=\"16\" />",
  ] },
  "circle-check": { paths: [
    "<circle cx=\"12\" cy=\"12\" r=\"10\" />",
    "<path d=\"m16 9-5.5 5.5L8 12\" />",
  ] },
  "clock": { paths: [
    "<circle cx=\"12\" cy=\"12\" r=\"10\" />",
    "<path d=\"M12 6v6l4 2\" />",
  ] },
  "copy": { paths: [
    "<rect width=\"14\" height=\"14\" x=\"8\" y=\"8\" rx=\"2\" ry=\"2\" />",
    "<path d=\"M4 16c-1.1 0-2-.9-2-2V4c0-1.1.9-2 2-2h10c1.1 0 2 .9 2 2\" />",
  ] },
  "gauge": { paths: [
    "<path d=\"m12 14 4-4\" />",
    "<path d=\"M3.34 19a10 10 0 1 1 17.32 0\" />",
  ] },
  "inbox": { paths: [
    "<polyline points=\"22 12 16 12 14 15 10 15 8 12 2 12\" />",
    "<path d=\"M5.45 5.11 2 12v6a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2v-6l-3.45-6.89A2 2 0 0 0 16.76 4H7.24a2 2 0 0 0-1.79 1.11z\" />",
  ] },
  "loader-circle": { paths: [
    "<path d=\"M21 12a9 9 0 1 1-6.219-8.56\" />",
  ] },
  "menu": { paths: [
    "<path d=\"M4 5h16\" />",
    "<path d=\"M4 12h16\" />",
    "<path d=\"M4 19h16\" />",
  ] },
  "message-square": { paths: [
    "<path d=\"M22 17a2 2 0 0 1-2 2H6.828a2 2 0 0 0-1.414.586l-2.202 2.202A.71.71 0 0 1 2 21.286V5a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2z\" />",
  ] },
  "panel-left": { paths: [
    "<rect width=\"18\" height=\"18\" x=\"3\" y=\"3\" rx=\"2\" />",
    "<path d=\"M9 3v18\" />",
  ] },
  "plug": { paths: [
    "<path d=\"M12 22v-5\" />",
    "<path d=\"M15 8V2\" />",
    "<path d=\"M17 8a1 1 0 0 1 1 1v4a4 4 0 0 1-4 4h-4a4 4 0 0 1-4-4V9a1 1 0 0 1 1-1z\" />",
    "<path d=\"M9 8V2\" />",
  ] },
  "plus": { paths: [
    "<path d=\"M5 12h14\" />",
    "<path d=\"M12 5v14\" />",
  ] },
  "power": { paths: [
    "<path d=\"M12 2v10\" />",
    "<path d=\"M18.4 6.6a9 9 0 1 1-12.77.04\" />",
  ] },
  "refresh-cw": { paths: [
    "<path d=\"M3 12a9 9 0 0 1 9-9 9.75 9.75 0 0 1 6.74 2.74L21 8\" />",
    "<path d=\"M21 3v5h-5\" />",
    "<path d=\"M21 12a9 9 0 0 1-9 9 9.75 9.75 0 0 1-6.74-2.74L3 16\" />",
    "<path d=\"M8 16H3v5\" />",
  ] },
  "search": { paths: [
    "<path d=\"m21 21-4.34-4.34\" />",
    "<circle cx=\"11\" cy=\"11\" r=\"8\" />",
  ] },
  "send": { paths: [
    "<path d=\"M14.536 21.686a.5.5 0 0 0 .937-.024l6.5-19a.496.496 0 0 0-.635-.635l-19 6.5a.5.5 0 0 0-.024.937l7.93 3.18a2 2 0 0 1 1.112 1.11z\" />",
    "<path d=\"m21.854 2.147-10.94 10.939\" />",
  ] },
  "settings": { paths: [
    "<path d=\"M9.671 4.136a2.34 2.34 0 0 1 4.659 0 2.34 2.34 0 0 0 3.319 1.915 2.34 2.34 0 0 1 2.33 4.033 2.34 2.34 0 0 0 0 3.831 2.34 2.34 0 0 1-2.33 4.033 2.34 2.34 0 0 0-3.319 1.915 2.34 2.34 0 0 1-4.659 0 2.34 2.34 0 0 0-3.32-1.915 2.34 2.34 0 0 1-2.33-4.033 2.34 2.34 0 0 0 0-3.831A2.34 2.34 0 0 1 6.35 6.051a2.34 2.34 0 0 0 3.319-1.915\" />",
    "<circle cx=\"12\" cy=\"12\" r=\"3\" />",
  ] },
  "sparkles": { paths: [
    "<path d=\"M11.017 2.814a1 1 0 0 1 1.966 0l1.051 5.558a2 2 0 0 0 1.594 1.594l5.558 1.051a1 1 0 0 1 0 1.966l-5.558 1.051a2 2 0 0 0-1.594 1.594l-1.051 5.558a1 1 0 0 1-1.966 0l-1.051-5.558a2 2 0 0 0-1.594-1.594l-5.558-1.051a1 1 0 0 1 0-1.966l5.558-1.051a2 2 0 0 0 1.594-1.594z\" />",
    "<path d=\"M20 2v4\" />",
    "<path d=\"M22 4h-4\" />",
    "<circle cx=\"4\" cy=\"20\" r=\"2\" />",
  ] },
  "square": { paths: [
    "<rect width=\"18\" height=\"18\" x=\"3\" y=\"3\" rx=\"2\" />",
  ] },
  "terminal": { paths: [
    "<path d=\"M12 19h8\" />",
    "<path d=\"m4 17 6-6-6-6\" />",
  ] },
  "trash-2": { paths: [
    "<path d=\"M10 11v6\" />",
    "<path d=\"M14 11v6\" />",
    "<path d=\"M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6\" />",
    "<path d=\"M3 6h18\" />",
    "<path d=\"M8 6V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2\" />",
  ] },
  "triangle-alert": { paths: [
    "<path d=\"m21.73 18-8-14a2 2 0 0 0-3.48 0l-8 14A2 2 0 0 0 4 21h16a2 2 0 0 0 1.73-3\" />",
    "<path d=\"M12 9v4\" />",
    "<path d=\"M12 17h.01\" />",
  ] },
  "x": { paths: [
    "<path d=\"M18 6 6 18\" />",
    "<path d=\"m6 6 12 12\" />",
  ] },
} as const;
